trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu:18.04

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    jdkVersionOption: '1.11'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
