# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2.1.0
        with:
          java-version: 11
      - name: Maven build
        run: mvn -B verify
      - name: Send to SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=murrayspeight -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@master"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      #- name: Publish to GitHub Packages Apache Maven
      #  run: mvn deploy -Drevision=${{ steps.semvers.outputs.patch }} -DskipTests
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}